#!/bin/bash
#
# Setup bash .profile

source os.sh
PROFILE_DIR=$(dirname $(${GNU}readlink -f $0))
ADDITIONAl_BASH_PROFILE=${PROFILE_DIR}/bash_profile
if [ ! -f $ADDITIONAl_BASH_PROFILE ]; then
    echo "Error: $ADDITIONAl_BASH_PROFILE doesn't exist!"
    exit 1
fi

BASH_PROFILE=$HOME/.profile
# Create .profile if non-existing
if [ ! -f $BASH_PROFILE ]; then
    echo "$BASH_PROFILE doesn't exist! Created it!"
    touch $BASH_PROFILE
fi
#Append the bash_profile to .profile
echo -e "\n#Envirnment variables set by $PROFILE_DIR/setup_bash">>$BASH_PROFILE
echo ". $ADDITIONAl_BASH_PROFILE">>$BASH_PROFILE
echo "Modified $BASH_PROFILE to include $ADDITIONAl_BASH_PROFILE"

