#!/bin/bash
#
# Setup user profile

source os.sh

# setup bash 
source $PROFILE_DIR/setup_bash

#vim
echo "Setup vim"
ln -sf $PROFILE_DIR/vim/.vimrc $HOME/.vimrc  
ln -sf $PROFILE_DIR/vim/.gvimrc $HOME/.gvimrc  
ln -sfn $PROFILE_DIR/vim/.vim $HOME/.vim  

#mercurial
echo "Setup mercurial"
ln -sf $PROFILE_DIR/mercurial/.hgrc $HOME/.hgrc  

#git
echo "Setup git"
ln -sf $PROFILE_DIR/git/.gitconfig $HOME/.gitconfig  

#indent
echo "Setup indent"
ln -sf $PROFILE_DIR/indent/.indent.pro $HOME/.indent.pro  

#astyle
echo "Setup astyle"
ln -sf $PROFILE_DIR/astyle/.astylerc $HOME/.astylerc  
#ibus-cloud-pinyin
echo "Setup ibus-cloud-pinyin"
USER_CLOUD_PINYIN_PATH=${XDG_CONFIG_HOME:-$HOME/.config}/ibus/cloud-pinyin
if [ ! -e $USER_CLOUD_PINYIN_PATH ]; then
    mkdir -p $USER_CLOUD_PINYIN_PATH
fi
ln -sf $PROFILE_DIR/ibus/cloud-pinyin/config.lua $USER_CLOUD_PINYIN_PATH/config.lua

#ctags
echo "Setup ctags"
ln -sf $PROFILE_DIR/ctags/.ctags $HOME/.ctags  

