#!/bin/bash
#
# Setup user profile

if [ ! -f os.sh ]; then
    echo "Error: os.h doesn't exist!"
    exit 1
fi
source os.sh
PROFILE_DIR=$(dirname $(${GNU}readlink -f $0))
ln -sf $PROFILE_DIR/os.sh $HOME/.os.sh

# setup bash 
SETUP_BASH=$PROFILE_DIR/setup_bash 
if [ ! -x $SETUP_BASH ]; then
    echo "Error: $SETUP_BASH doesn't exist!"
    exit 1
fi
$PROFILE_DIR/setup_bash

#vim
echo "Setup vim"
ln -sf $PROFILE_DIR/vim/.vimrc $HOME/.vimrc  
ln -sf $PROFILE_DIR/vim/.gvimrc $HOME/.gvimrc  
ln -sfn $PROFILE_DIR/vim/.vim $HOME/.vim  

#mercurial
echo "Setup mercurial"
ln -sf $PROFILE_DIR/mercurial/.hgrc $HOME/.hgrc  

#git
echo "Setup git"
ln -sf $PROFILE_DIR/git/.gitconfig $HOME/.gitconfig  

#ctags
echo "Setup ctags"
ln -sf $PROFILE_DIR/ctags/.ctags $HOME/.ctags  

